// generate-env.js
// Reads environment variables and generates public/env.js

const fs = require('fs');
const path = require('path');


require('dotenv').config();

const envVars = [
    'FIREBASE_API_KEY',
    'FIREBASE_AUTH_DOMAIN',
    'FIREBASE_PROJECT_ID',
    'FIREBASE_STORAGE_BUCKET',
    'FIREBASE_MESSAGING_SENDER_ID',
    'FIREBASE_APP_ID',
    'FIREBASE_APP_KEY'
];

let envContent = '// This file is generated by generate-env.js\n';

envVars.forEach(varName => {
    // Use NEXT_PUBLIC_ prefix for Vercel compatibility
    const vercelVarName = `NEXT_PUBLIC_${varName}`;
    const value = process.env[vercelVarName] || process.env[varName]; // Check both NEXT_PUBLIC_ and original
    if (value) {
        envContent += `window.${varName} = "${value}";\n`;
    } else {
        // Optional: Log a warning if a variable is missing
        console.warn(`Environment variable ${vercelVarName} or ${varName} is not set.`);
    }
});

const envFilePath = path.join(__dirname, 'env.js'); // env.js dosyasını doğrudan kök dizine oluştur

fs.writeFileSync(envFilePath, envContent);

console.log(`Generated ${envFilePath}`);
